repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v2.3.0
  hooks:
  - id: check-yaml
    exclude: ^terraform/modules/helm/charts/
  - id: end-of-file-fixer
  - id: trailing-whitespace
  - id: check-added-large-files
  - id: check-case-conflict
  - id: check-json

- repo: https://github.com/yelp/detect-secrets
  rev: v1.4.0
  hooks:
  - id: detect-secrets
    args: ['--baseline', '.secrets.baseline']

- repo: local
  hooks:
  - id: lint
    name: Run API Formatting & Linting
    entry: make -C api lint
    language: system
    pass_filenames: false
    files: ^api/

  - id: unittests
    name: Run API Unit Tests
    entry: make -C api run-tests
    language: system
    pass_filenames: false
    files: ^api/

- repo: local
  hooks:
  - id: lint
    name: Run TF Formatting & Linting
    entry: make -C terraform lint
    language: system
    pass_filenames: false
    files: ^terraform/

- repo: local
  hooks:
  - id: lint
    name: Run Alembic Formatting & Linting
    entry: make -C alembic lint
    language: system
    pass_filenames: false
    files: ^alembic/
