name: Deploy
on:
  push:
    branches:
      - dev
      - master

jobs:
  deploy:
    needs: unittests
    uses: ./.github/workflows/tf.yaml
    name: Terraform Plan Only
    with:
      environment: ${{ github.event.pull_request.base.ref == 'master' && 'prod' || 'dev' }}
      aws_region: eu-west-2
      plan_only: false
    secrets:
      kubeconfig: ${{ secrets.KUBE_CONFIG_DATA }}
      aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
