name: Integration Tests
on:
  workflow_call:
    secrets:
      kubeconfig:
        required: true
      api_key:
        required: true

jobs:
  load-seed-data:
    runs-on: ubuntu-latest
    name: Load Seed Data
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          version=$(sudo curl -L -s https://dl.k8s.io/release/stable.txt)
          echo "Installing kubectl version $version"

          sudo curl -LO "https://dl.k8s.io/release/$version/bin/linux/amd64/kubectl"
          sudo install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl

          mkdir -p $HOME/.kube

          echo "${KUBE_CONFIG}" | base64 -d > $HOME/.kube/config
        env:
          KUBE_CONFIG: ${{ secrets.kubeconfig }}

      - name: Seed Test Environment
        working-directory: ./manifests
        run: |
          kubectl replace --force -f load_seed_data.yaml

  run-integration-tests:
    runs-on: ubuntu-latest
    needs: load-seed-data
    name: Run Integration Tests
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker
        uses: docker/setup-docker-action@v4

      - name: Install dependencies
        run: |
          sudo apt-get update && \
            sudo apt-get install -y make

      - name: Run Integration Tests
        working-directory: ./acceptance
        run: |
          echo "Running integration tests..."
          make run-tests
        env:
          ADMIN_API_KEY: ${{ secrets.api_key }}
