name: Deploy
on:
  push:
    branches:
      - dev
      - master

jobs:
  plan-global:
    uses: ./.github/workflows/tf-plan.yaml
    name: Terraform Global (Plan Only)
    with:
      environment: global
      aws_region: eu-west-2
      aws_assume_role_arn: ${{ vars.AWS_ASSUME_ROLE_ARN }}
      aws_dynamodb_statelock_table: ${{ vars.AWS_DYNAMODB_STATELOCK_TABLE }}
      aws_s3_backend_bucket: ${{ vars.AWS_S3_BACKEND_BUCKET }}
    secrets:
      kubeconfig: ${{ secrets.KUBE_CONFIG_DATA }}
      aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

  deploy-global:
    uses: ./.github/workflows/tf-apply.yaml
    needs: plan-global
    name: Terraform Global (Apply)
    with:
      environment: global
      aws_region: eu-west-2
      aws_assume_role_arn: ${{ vars.AWS_ASSUME_ROLE_ARN }}
      aws_dynamodb_statelock_table: ${{ vars.AWS_DYNAMODB_STATELOCK_TABLE }}
      aws_s3_backend_bucket: ${{ vars.AWS_S3_BACKEND_BUCKET }}
    secrets:
      kubeconfig: ${{ secrets.KUBE_CONFIG_DATA }}
      aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

  plan-environment:
    uses: ./.github/workflows/tf-plan.yaml
    name: Terraform Environment (Plan Only)
    with:
      environment: ${{ github.ref_name == 'master' && 'prod' || 'dev' }}
      aws_region: eu-west-2
      aws_assume_role_arn: ${{ vars.AWS_ASSUME_ROLE_ARN }}
      aws_dynamodb_statelock_table: ${{ vars.AWS_DYNAMODB_STATELOCK_TABLE }}
      aws_s3_backend_bucket: ${{ vars.AWS_S3_BACKEND_BUCKET }}
    secrets:
      kubeconfig: ${{ secrets.KUBE_CONFIG_DATA }}
      aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

  deploy-environment:
    uses: ./.github/workflows/tf-apply.yaml
    needs: plan-environment
    name: Terraform Environment (Apply)
    with:
      environment: ${{ github.ref_name == 'master' && 'prod' || 'dev' }}
      aws_region: eu-west-2
      aws_assume_role_arn: ${{ vars.AWS_ASSUME_ROLE_ARN }}
      aws_dynamodb_statelock_table: ${{ vars.AWS_DYNAMODB_STATELOCK_TABLE }}
      aws_s3_backend_bucket: ${{ vars.AWS_S3_BACKEND_BUCKET }}
    secrets:
      kubeconfig: ${{ secrets.KUBE_CONFIG_DATA }}
      aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

  integration-tests:
    uses: ./.github/workflows/integration-tests.yaml
    needs: deploy-environment
    name: Integration Tests
    secrets:
      kubeconfig: ${{ secrets.KUBE_CONFIG_DATA }}
