name: Terraform Plan
on:
  workflow_call:
    secrets:
      kubeconfig:
        required: true
      aws_access_key_id:
        required: true
      aws_secret_access_key:
        required: true
    inputs:
      environment:
        required: true
        type: string
      aws_region:
        required: false
        type: string
        default: eu-west-2
      aws_assume_role_arn:
        required: true
        type: string
      aws_dynamodb_statelock_table:
        required: true
        type: string
      aws_s3_backend_bucket:
        required: true
        type: string

jobs:
  tf-plan:
    runs-on: ubuntu-latest
    name: Terraform Plan
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.aws_access_key_id }}
          aws-secret-access-key: ${{ secrets.aws_secret_access_key }}
          aws-region: ${{ inputs.aws_region }}

      - name: Install dependencies
        run: |
          version=$(sudo curl -L -s https://dl.k8s.io/release/stable.txt)
          echo "Installing kubectl version $version"

          sudo curl -LO "https://dl.k8s.io/release/$version/bin/linux/amd64/kubectl"
          sudo install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl

          mkdir -p $HOME/.kube

          echo "${KUBE_CONFIG}" | base64 -d > $HOME/.kube/config
        env:
          KUBE_CONFIG: ${{ secrets.kubeconfig }}

      - name: Run Terraform Plan
        working-directory: ./terraform/env/${{ inputs.environment }}
        run: |
          echo "Running Terraform plan..."
          terraform init -backend-config="bucket=${{ inputs.aws_s3_backend_bucket }}" \
            -backend-config="region=${{ inputs.aws_region }}" \
            -backend-config="dynamodb_table=${{ inputs.aws_dynamodb_statelock_table }}" \
            -backend-config="assume_role={ role_arn = \"${{ inputs.aws_assume_role_arn }}\" }"

          terraform plan -var="aws_region=${{ inputs.aws_region }}" \
            -var="aws_assume_role_arn=${{ inputs.aws_assume_role_arn }}"
